# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_auto_20190920_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
